const sets = [
// Empty sets
    // Promos
    {
        "id": "P",
        "name": "Promos",
        "release": null,
        "total": 81,
        "url": null,
        "add_zero": 3,
        "info_url": null
    },
    // Booster New Evolution [BT1]
    {
        "id": "BT1",
        "name": "Booster New Evolution [BT1]",
        "release": null,
        "total": 115,
        "url": null,
        "add_zero": 3,
        "info_url": null
    },
    // Booster Ultimate Power [BT2]
    {
        "id": "BT2",
        "name": "Booster Ultimate Power [BT2]",
        "release": null,
        "total": 112,
        "url": null,
        "add_zero": 3,
        "info_url": null
    },
    // Booster Union Impact [BT3]
    {
        "id": "BT3",
        "name": "Booster Union Impact [BT3]",
        "release": null,
        "total": 112,
        "url": null,
        "add_zero": 3,
        "info_url": null
    },

    // Promotion Pack Ver.0.0
    {
        "id": null,
        "name": "Promotion Pack Ver.0.0",
        "release": null,
        "url": "bandaitcgplusURL/setID/setID-cardID.png",
        "cards": {
            "P-001": "",
            "P-002": "",
            "P-003": "",
            "P-004": "",
            "P-005": "",
            "P-006": ""
        },
    },

// January 29th,2021
    // Starter Deck GAIA RED [ST-1]
    {
        "id": "ST1",
        "name": "Starter Deck GAIA RED [ST-1]",
        "release": "January 29th,2021",
        "total": 16,
        "url": "bandaitcgplusURL/setID/setID-cardID.png",
        "add_zero": 2,
        "info_url": "https://world.digimoncard.com/products/deck/st-1.php"
    },
    // Starter Deck COCYTUS BLUE [ST-2]
    {
        "id": "ST2",
        "name": "Starter Deck COCYTUS BLUE [ST-2]",
        "release": "January 29th,2021",
        "total": 16,
        "url": "bandaitcgplusURL/setID/setID-cardID.png",
        "add_zero": 2,
        "info_url": "https://world.digimoncard.com/products/deck/st-2.php"
    },
    // Starter Deck HEAVEN'S YELLOW [ST-3]
    {
        "id": "ST3",
        "name": "Starter Deck HEAVEN'S YELLOW [ST-3]",
        "release": "January 29th,2021",
        "total": 16,
        "url": "bandaitcgplusURL/setID/setID-cardID.png",
        "add_zero": 2,
        "info_url": "https://world.digimoncard.com/products/deck/st-3.php"
    },

// February 12, 2021
    // Release Special Booster Ver.1.0 [BT01-03]
    {
        "id": null,
        "name": "Release Special Booster Ver.1.0 [BT01-03]",
        "release": "February 12, 2021",
        "url": "bandaitcgplusURL/setID/setID-cardID.png",
        "cards": {
            "BT1-001": "",
            "BT1-002": "",
            "BT1-003": "",
            "BT1-004": "",
            "BT1-005": "",
            "BT1-006": "",
            "BT1-007": "",
            "BT1-008": "",
            "BT1-009": "",
            "BT1-010": "",
            "BT1-011": "",
            "BT1-012": "",
            "BT1-013": "",
            "BT1-014": "",
            "BT1-015": "",
            "BT1-016": "",
            "BT1-017": "",
            "BT1-018": "",
            "BT1-019": "",
            "BT1-020": "",
            "BT1-021": "",
            "BT1-022": "",
            "BT1-023": "",
            "BT1-024": "",
            "BT1-025": "",
            "BT1-026": "",
            "BT1-027": "",
            "BT1-028": "",
            "BT1-029": "",
            "BT1-030": "",
            "BT1-031": "",
            "BT1-032": "",
            "BT1-033": "",
            "BT1-034": "",
            "BT1-035": "",
            "BT1-036": "",
            "BT1-037": "",
            "BT1-038": "",
            "BT1-039": "",
            "BT1-040": "",
            "BT1-041": "",
            "BT1-042": "",
            "BT1-043": "",
            "BT1-044": "",
            "BT1-045": "",
            "BT1-046": "",
            "BT1-047": "",
            "BT1-048": "",
            "BT1-049": "",
            "BT1-050": "",
            "BT1-051": "",
            "BT1-052": "",
            "BT1-053": "",
            "BT1-054": "",
            "BT1-055": "",
            "BT1-056": "",
            "BT1-057": "",
            "BT1-058": "",
            "BT1-059": "",
            "BT1-060": "",
            "BT1-061": "",
            "BT1-062": "",
            "BT1-063": "",
            "BT1-064": "",
            "BT1-065": "",
            "BT1-066": "",
            "BT1-067": "",
            "BT1-068": "",
            "BT1-069": "",
            "BT1-070": "",
            "BT1-071": "",
            "BT1-072": "",
            "BT1-073": "",
            "BT1-074": "",
            "BT1-075": "",
            "BT1-076": "",
            "BT1-077": "",
            "BT1-078": "",
            "BT1-079": "",
            "BT1-080": "",
            "BT1-081": "",
            "BT1-082": "",
            "BT1-084": "",
            "BT1-085": "",
            "BT1-086": "",
            "BT1-087": "",
            "BT1-088": "",
            "BT1-089": "",
            "BT1-090": "",
            "BT1-092": "",
            "BT1-093": "",
            "BT1-094": "",
            "BT1-096": "",
            "BT1-097": "",
            "BT1-098": "",
            "BT1-099": "",
            "BT1-102": "",
            "BT1-104": "",
            "BT1-105": "",
            "BT1-106": "",
            "BT1-108": "",
            "BT1-109": "",
            "BT1-110": "",
            "BT1-111": "",
            "BT1-112": "",
            "BT1-113": "",
            "BT1-114": "",
            "BT1-115": "",
            "BT2-005": "",
            "BT2-006": "",
            "BT2-007": "",
            "BT2-008": "",
            "BT2-009": "",
            "BT2-013": "",
            "BT2-017": "",
            "BT2-018": "",
            "BT2-020": "",
            "BT2-030": "",
            "BT2-039": "",
            "BT2-043": "",
            "BT2-044": "",
            "BT2-046": "",
            "BT2-048": "",
            "BT2-049": "",
            "BT2-051": "",
            "BT2-052": "",
            "BT2-053": "",
            "BT2-054": "",
            "BT2-055": "",
            "BT2-056": "",
            "BT2-057": "",
            "BT2-058": "",
            "BT2-059": "",
            "BT2-060": "",
            "BT2-061": "",
            "BT2-062": "",
            "BT2-063": "",
            "BT2-064": "",
            "BT2-065": "",
            "BT2-066": "",
            "BT2-067": "",
            "BT2-068": "",
            "BT2-069": "",
            "BT2-070": "",
            "BT2-071": "",
            "BT2-072": "",
            "BT2-073": "",
            "BT2-074": "",
            "BT2-075": "",
            "BT2-076": "",
            "BT2-077": "",
            "BT2-078": "",
            "BT2-079": "",
            "BT2-080": "",
            "BT2-081": "",
            "BT2-082": "",
            "BT2-083": "",
            "BT2-084": "",
            "BT2-085": "",
            "BT2-087": "",
            "BT2-088": "",
            "BT2-089": "",
            "BT2-090": "",
            "BT2-092": "",
            "BT2-093": "",
            "BT2-095": "",
            "BT2-102": "",
            "BT2-103": "",
            "BT2-104": "",
            "BT2-105": "",
            "BT2-106": "",
            "BT2-107": "",
            "BT2-108": "",
            "BT2-109": "",
            "BT2-110": "",
            "BT2-111": "",
            "BT3-030": "",
            "BT3-043": "",
            "BT3-061": "",
            "BT3-074": "",
            "BT3-079": "",
            "BT3-081": "",
            "BT3-084": "",
            "BT3-089": "",
            "BT3-091": "",
            "BT3-107": "",
            "BT3-109": "",
        },
        "info_url": null
    },
    // Release Special Booster Ver.1.0 [BT01-03] - Alternatives
    {
        "id": null,
        "name": "Release Special Booster Ver.1.0 [BT01-03] - Alternatives",
        "release": "February 12, 2021",
        "url": "bandaitcgplusURL/setID/setID-cardID_parallel.png",
        "cards": {
            "BT1-025": "P1",
            "BT1-044": "P1",
            "BT1-060": "P1",
            "BT1-082": "P1",
            "BT1-084": "P1",
            "BT1-110": "P1",
            "BT1-114": "P1",
            "BT1-115": "P1",
            "BT2-020": "P1",
            "BT2-065": "P1",
            "BT2-080": "P1",
            "BT2-081": "P1",
            "BT2-082": "P1",
            "BT2-111": "P1",
            "BT3-030": "P1",
            "BT3-043": "P1",
            "BT3-091": "P1",
        },
    },
    // Release Special Booster Ver.1.0 [BT01-03] - Box Topper
    {
        "id": null,
        "name": "Release Special Booster Ver.1.0 [BT01-03] - Box Topper",
        "release": "February 12, 2021",
        "url": "bandaitcgplusURL/setID/setID-cardID_parallel.png",
        "cards": {
            "BT1-085": "P1",
            "BT1-086": "P1",
            "BT1-087": "P1",
            "BT1-088": "P1",
            "BT1-089": "P1",
            "BT2-084": "P1",
            "BT2-085": "P1",
            "BT2-087": "P1",
            "BT2-089": "P1",
            "BT2-090": "P1",
        },
    },
    // Special Box Promotion Pack
    {
        "id": null,
        "name": "Special Box Promotion Pack",
        "release": "February 12, 2021",
        "url": "bandaitcgplusURL/setID/setID-cardID.png",
        "cards": {
            "P-007": "",
            "P-008": "",
            "P-009": "",
            "P-010": "",
            "P-011": "",
            "P-012": ""
        },
    },
    // Dash Pack Ver. 1.0
    {
        "id": null,
        "name": "Dash Pack Ver. 1.0",
        "release": "February 12, 2021",
        "url": "bandaitcgplusURL/setID/setID-cardID_parallel.png",
        "cards": {
            "BT1-010": "P1",
            "BT1-029": "P1",
            "BT2-030": "P1",
            "BT2-049": "P1",
            "BT2-066": "P1"
        },
    },

// February, 2021
    // Tamer's Evolution Box [PB-01]
    {
        "id": null,
        "name": "Tamer's Evolution Box [PB-01]",
        "release": "February, 2021",
        "url": "bandaitcgplusURL/setID/setID-cardID_parallel.png",
        "cards": {
            "ST1-13": "P1",
            "ST1-16": "P1",
            "ST2-13": "P1",
            "ST2-16": "P1",
            "ST3-13": "P1",
            "ST3-14": "P1",
            "BT1-108": "P1",
            "BT1-110": "P2",
        },
        "info_url": "https://world.digimoncard.com/products/goods/evolution-box.php"

    },

// March 12, 2021
    // Release Special Booster Ver.1.5 [BT01-03]
    {
        "id": null,
        "name": "Release Special Booster Ver.1.5 [BT01-03]",
        "release": "March 12, 2021",
        "url": "bandaitcgplusURL/setID/setID-cardID.png",
        "cards": {
            "BT1-083": "",
            "BT1-091": "",
            "BT1-095": "",
            "BT1-100": "",
            "BT1-101": "",
            "BT1-103": "",
            "BT1-107": "",
            "BT2-001": "",
            "BT2-002": "",
            "BT2-003": "",
            "BT2-004": "",
            "BT2-010": "",
            "BT2-011": "",
            "BT2-012": "",
            "BT2-014": "",
            "BT2-015": "",
            "BT2-016": "",
            "BT2-019": "",
            "BT2-021": "",
            "BT2-022": "",
            "BT2-023": "",
            "BT2-024": "",
            "BT2-025": "",
            "BT2-026": "",
            "BT2-027": "",
            "BT2-028": "",
            "BT2-029": "",
            "BT2-031": "",
            "BT2-032": "",
            "BT2-033": "",
            "BT2-034": "",
            "BT2-035": "",
            "BT2-036": "",
            "BT2-037": "",
            "BT2-038": "",
            "BT2-040": "",
            "BT2-041": "",
            "BT2-042": "",
            "BT2-045": "",
            "BT2-047": "",
            "BT2-050": "",
            "BT2-086": "",
            "BT2-091": "",
            "BT2-094": "",
            "BT2-096": "",
            "BT2-097": "",
            "BT2-098": "",
            "BT2-099": "",
            "BT2-100": "",
            "BT2-101": "",
            "BT2-112": "",
            "BT3-001": "",
            "BT3-002": "",
            "BT3-003": "",
            "BT3-004": "",
            "BT3-005": "",
            "BT3-006": "",
            "BT3-007": "",
            "BT3-008": "",
            "BT3-009": "",
            "BT3-010": "",
            "BT3-011": "",
            "BT3-012": "",
            "BT3-013": "",
            "BT3-014": "",
            "BT3-015": "",
            "BT3-016": "",
            "BT3-017": "",
            "BT3-018": "",
            "BT3-019": "",
            "BT3-020": "",
            "BT3-021": "",
            "BT3-022": "",
            "BT3-023": "",
            "BT3-024": "",
            "BT3-025": "",
            "BT3-026": "",
            "BT3-027": "",
            "BT3-028": "",
            "BT3-029": "",
            "BT3-031": "",
            "BT3-032": "",
            "BT3-033": "",
            "BT3-034": "",
            "BT3-035": "",
            "BT3-036": "",
            "BT3-037": "",
            "BT3-038": "",
            "BT3-039": "",
            "BT3-040": "",
            "BT3-041": "",
            "BT3-042": "",
            "BT3-044": "",
            "BT3-045": "",
            "BT3-046": "",
            "BT3-047": "",
            "BT3-048": "",
            "BT3-049": "",
            "BT3-050": "",
            "BT3-051": "",
            "BT3-052": "",
            "BT3-053": "",
            "BT3-054": "",
            "BT3-055": "",
            "BT3-056": "",
            "BT3-057": "",
            "BT3-058": "",
            "BT3-059": "",
            "BT3-060": "",
            "BT3-062": "",
            "BT3-063": "",
            "BT3-064": "",
            "BT3-065": "",
            "BT3-066": "",
            "BT3-067": "",
            "BT3-068": "",
            "BT3-069": "",
            "BT3-070": "",
            "BT3-071": "",
            "BT3-072": "",
            "BT3-073": "",
            "BT3-075": "",
            "BT3-076": "",
            "BT3-077": "",
            "BT3-078": "",
            "BT3-080": "",
            "BT3-082": "",
            "BT3-083": "",
            "BT3-085": "",
            "BT3-086": "",
            "BT3-087": "",
            "BT3-088": "",
            "BT3-090": "",
            "BT3-092": "",
            "BT3-093": "",
            "BT3-094": "",
            "BT3-095": "",
            "BT3-096": "",
            "BT3-097": "",
            "BT3-098": "",
            "BT3-099": "",
            "BT3-100": "",
            "BT3-101": "",
            "BT3-102": "",
            "BT3-103": "",
            "BT3-104": "",
            "BT3-105": "",
            "BT3-106": "",
            "BT3-108": "",
            "BT3-110": "",
            "BT3-111": "",
            "BT3-112": "",
        },
        "info_url": null
    },
    // Release Special Booster Ver.1.5 [BT01-03] - Alternatives
    {
        "id": null,
        "name": "Release Special Booster Ver.1.5 [BT01-03] - Alternatives",
        "release": "March 12, 2021",
        "url": "bandaitcgplusURL/setID/setID-cardID_parallel.png",
        "cards": {
            "BT2-032": "P1",
            "BT2-041": "P1",
            "BT2-112": "P1",
            "BT3-031": "P1",
            "BT3-056": "P1",
            "BT3-073": "P1",
            "BT3-075": "P1",
            "BT3-090": "P1",
            "BT3-111": "P1",
            "BT3-112": "P1",
        },
    },
    // Release Special Booster Ver.1.5 [BT01-03] - Box Topper
    {
        "id": null,
        "name": "Release Special Booster Ver.1.5 [BT01-03] - Box Topper",
        "release": "March 12, 2021",
        "url": "bandaitcgplusURL/setID/setID-cardID_parallel.png",
        "cards": {
            "BT3-011": "P1",
            "BT3-024": "P1",
            "BT3-036": "P1",
            "BT3-049": "P1",
            "BT3-065": "P1",
            "BT3-082": "P1",
        },
    },
    // Dash Pack Ver. 1.5
    {
        "id": null,
        "name": "Dash Pack Ver. 1.5",
        "release": "March 12, 2021",
        "url": "bandaitcgplusURL/setID/setID-cardID_parallel.png",
        "cards": {
            "BT1-083": "P1",
            "BT1-095": "P1",
            "BT1-101": "P1",
            "BT1-107": "P1",
            "BT3-019": "P1"
        },
    },
    // Special Release Memorial Pack!
    {
        "id": null,
        "name": "Special Release Memorial Pack!",
        "release": "March 12, 2021",
        "url": "bandaitcgplusURL/setID/setID-cardID.png",
        "cards": {
            "P-021": "",
            "P-022": "",
            "P-023": "",
            "P-024": "",
        },
    },

// May 28th, 2021
    // Premium Pack Set 01
    {
        "id": null,
        "name": "Premium Pack Set 01",
        "release": "May 28th, 2021",
        "url": "bandaitcgplusURL/setID/setID-cardID_parallel.png",
        "cards": {
            "BT2-038": "P1",
        },
        "info_url": "https://world.digimoncard.com/products/goods/premium_pack.php"
    },

// June 11, 2021
    // Starter Deck GIGA GREEN [ST-4]
    {
        "id": "ST4",
        "name": "Starter Deck GIGA GREEN [ST-4]",
        "release": "June 11, 2021",
        "total": 16,
        "url": "bandaitcgplusURL/setID/setID-cardID.png",
        "add_zero": 2,
        "info_url": "https://world.digimoncard.com/products/deck/st-4.php"
    },
    // Starter Deck MACHINE BLACK [ST-5]
    {
        "id": "ST5",
        "name": "Starter Deck MACHINE BLACK [ST-5]",
        "release": "June 11, 2021",
        "total": 16,
        "url": "bandaitcgplusURL/setID/setID-cardID.png",
        "add_zero": 2,
        "info_url": "https://world.digimoncard.com/products/deck/st-5.php"
    },
    // Starter Deck VENOMOUS VIOLET [ST-6]
    {
        "id": "ST6",
        "name": "Starter Deck VENOMOUS VIOLET [ST-6]",
        "release": "June 11, 2021",
        "total": 16,
        "url": "bandaitcgplusURL/setID/setID-cardID.png",
        "add_zero": 2,
        "info_url": "https://world.digimoncard.com/products/deck/st-6.php"
    },

    // Booster Great Legend [BT4]
    {
        "id": "BT4",
        "name": "Booster Great Legend [BT4]",
        "release": "June 11, 2021",
        "total": 115,
        "url": "bandaitcgplusURL/setID/setID-cardID.png",
        "add_zero": 3
    },
    // Booster Great Legend [BT4] - Alternatives
    {
        "id": null,
        "name": "Booster Great Legend [BT4] - Alternatives",
        "release": "June 11, 2021",
        "url": "bandaitcgplusURL/setID/setID-cardID_parallel.png",
        "cards": {
            "BT4-011": "P1",
            "BT4-017": "P1",
            "BT4-019": "P1",
            "BT4-025": "P1",
            "BT4-033": "P1",
            "BT4-035": "P1",
            "BT4-048": "P1",
            "BT4-059": "P1",
            "BT4-062": "P1",
            "BT4-075": "P1",
            "BT4-088": "P1",
            "BT4-090": "P1",
            "BT4-113": "P1",
            "BT4-114": "P1",
            "BT4-115": "P1",
        },
    },
    // Booster Great Legend [BT4] - Box Topper
    {
        "id": null,
        "name": "Booster Great Legend [BT4] - Box Topper",
        "release": "June 11, 2021",
        "url": "bandaitcgplusURL/setID/setID-cardID_parallel.png",
        "cards": {
            "BT4-092": "P1",
            "BT4-093": "P1",
            "BT4-094": "P1",
            "BT4-095": "P1",
            "BT4-096": "P1",
            "BT4-097": "P1"
        },
    },
    // Great Dash Pack
    {
        "id": null,
        "name": "Great Dash Pack",
        "release": "June 11, 2021",
        "url": "bandaitcgplusURL/setID/setID-cardID.png",
        "cards": {
            "P-025": "",
            "P-026": "",
            "P-027": "",
        },
    },
    // Great Legend Power Up Pack
    {
        "id": null,
        "name": "Great Legend Power Up Pack",
        "release": "June 11, 2021",
        "url": "bandaitcgplusURL/setID/setID-cardID.png",
        "cards": {
            "P-029": "",
            "P-030": "",
            "P-031": "",
            "P-032": "",
            "P-033": "",
            "P-034": "",
        },
    },

// August 6, 2021
    // Booster Battle of Omni [BT5]
    {
        "id": "BT5",
        "name": "Booster Battle of Omni [BT5]",
        "release": "August 6, 2021",
        "total": 112,
        "url": "bandaitcgplusURL/setID/setID-cardID.png",
        "add_zero": 3
    },
    // Booster Battle of Omni [BT5] - Alternatives
    {
        "id": null,
        "name": "Booster Battle of Omni [BT5] - Alternatives",
        "release": "August 6, 2021",
        "url": "bandaitcgplusURL/setID/setID-cardID_parallel.png",
        "cards": {
            "BT5-019": "P1",
            "BT5-081": ["P1", "P2"],
            "BT5-085": "P1",
            "BT5-086": ["P1", "P2", "P3", "P4"],
            "BT5-087": ["P1", "P2"],
            "BT5-111": "P1",
            "BT5-112": "P1",
        },
    },
    // Booster Battle of Omni [BT5] - Box Topper
    {
        "id": null,
        "name": "Booster Battle of Omni [BT5] - Box Topper",
        "release": "August 6, 2021",
        "url": "bandaitcgplusURL/setID/setID-cardID_parallel.png",
        "cards": {
            "BT5-088": "P1",
            "BT5-089": "P1",
            "BT5-090": "P1",
            "BT5-091": "P1",
            "BT5-092": "P1",
            "BT5-093": "P1",
        },
    },

// October, 2021
    // Official Tournament Pack Vol.1
    {
        "id": null,
        "name": "Official Tournament Pack Vol.1",
        "release": "October, 2021",
        "url": "bandaitcgplusURL/setID/setID-cardID.png",
        "cards": {
            "P-013": "",
            "P-014": "",
            "P-015": "",
            "P-016": "",
            "P-017": "",
            "P-018": "",
            "P-019": "",
            "P-020": "",
        },
    },

// October 15, 2021
    // Starter Deck GALLANTMON [ST-7]
    {
        "id": "ST7",
        "name": "Starter Deck GALLANTMON [ST-7]",
        "release": "October 15, 2021",
        "total": 12,
        "url": "bandaitcgplusURL/setID/setID-cardID.png",
        "add_zero": 2,
        "info_url": "https://world.digimoncard.com/products/deck/st-7.php"
    },
    // Starter Deck ULFORCEVEEDRAMON [ST-8]
    {
        "id": "ST8",
        "name": "Starter Deck ULFORCEVEEDRAMON [ST-8]",
        "release": "October 15, 2021",
        "total": 12,
        "url": "bandaitcgplusURL/setID/setID-cardID.png",
        "add_zero": 2,
        "info_url": "https://world.digimoncard.com/products/deck/st-8.php"
    },
    // First Anniversary Promo Pack
    {
        "id": null,
        "name": "First Anniversary Promo Pack",
        "release": "October 15, 2021",
        "url": "bandaitcgplusURL/setID/setID-cardID.png",
        "cards": {
            "P-035": "",
            "P-036": "",
            "P-037": "",
            "P-038": "",
            "P-039": "",
            "P-040": "",
        },
    },

    // Booster Double Diamond [BT6]
    {
        "id": "BT6",
        "name": "Booster Double Diamond [BT6]",
        "release": "October 15, 2021",
        "total": 112,
        "url": "bandaitcgplusURL/setID/setID-cardID.png",
        "add_zero": 3,
    },
    // Booster Double Diamond [BT6] - Alternatives
    {
        "id": null,
        "name": "Booster Double Diamond [BT6] - Alternatives",
        "release": "October 15, 2021",
        "url": "bandaitcgplusURL/setID/setID-cardID_parallel.png",
        "cards": {
            "BT6-007": "P1",
            "BT6-016": "P1",
            "BT6-018": "P1",
            "BT6-019": "P1",
            "BT6-030": "P1",
            "BT6-033": "P1",
            "BT6-044": "P1",
            "BT6-047": "P1",
            "BT6-064": "P1",
            "BT6-067": "P1",
            "BT6-068": "P1",
            "BT6-078": "P1",
            "BT6-081": "P1",
            "BT6-082": "P1",
            "BT6-084": "P1",
            "BT6-086": "P1",
            "BT6-111": "P1",
            "BT6-112": "P1",
            "BT1-084": "P3",
        },
    },
    // Booster Double Diamond [BT6] - Box Topper
    {
        "id": null,
        "name": "Booster Double Diamond [BT6] - Box Topper",
        "release": "October 15, 2021",
        "url": "bandaitcgplusURL/setID/setID-cardID_parallel.png",
        "cards": {
            "BT6-001": "P1",
            "BT6-002": "P1",
            "BT6-003": "P1",
            "BT6-004": "P1",
            "BT6-005": "P1",
            "BT6-006": "P1",
        },
    },
    // 1-Year Anniversary Promo Pack
    {
        "id": null,
        "name": "1-Year Anniversary Promo Pack",
        "release": "October 15, 2021",
        "url": "bandaitcgplusURL/setID/setID-cardID_parallel.png",
        "cards": {
            "ST1-10": "P1",
            "BT1-003": "P1",
            "BT2-074": "P1",
            "BT2-083": "P1",
            "BT3-021": "P1",
            "BT3-039": "P1",
            "BT3-046": "P1",
            "BT3-057": "P1",
            "BT4-016": "P1",
            "BT4-091": "P1",
        },
    },
    // Double Diamond Dash Pack
    {
        "id": null,
        "name": "Double Diamond Dash Pack",
        "release": "October 15, 2021",
        "url": "bandaitcgplusURL/setID/setID-cardID.png",
        "cards": {
            "P-041": "",
            "P-042": "",
            "P-043": "",
            "P-044": "",
            "P-045": "",
            "P-046": "",
        },
    },

// December 10, 2021
    // Booster Classic Collection [EX1]
    {
        "id": "EX1",
        "name": "Booster Classic Collection [EX1]",
        "release": "December 10, 2021",
        "total": 73,
        "url": "bandaitcgplusURL/setID/EX-cardID.png",
        "add_zero": 3
    },
    // Booster Classic Collection [EX1] - Alternatives
    {
        "id": null,
        "name": "Booster Classic Collection [EX1] - Alternatives",
        "release": "December 10, 2021",
        "url": "bandaitcgplusURL/setID/EX-cardIDp.png",
        "cards": {
            "EX1-001": "",
            "EX1-002": "",
            "EX1-004": "",
            "EX1-005": "",
            "EX1-006": "",
            "EX1-008": "",
            "EX1-009": "",
            "EX1-011": "",
            "EX1-012": "",
            "EX1-015": "",
            "EX1-017": "",
            "EX1-018": "",
            "EX1-019": "",
            "EX1-021": "",
            "EX1-022": "",
            "EX1-024": "",
            "EX1-026": "",
            "EX1-029": "",
            "EX1-030": "",
            "EX1-033": "",
            "EX1-034": "",
            "EX1-037": "",
            "EX1-039": "",
            "EX1-040": "",
            "EX1-043": "",
            "EX1-059": "",
            "EX1-063": "",
            "EX1-065": "",
            "EX1-066": "",
            "EX1-073": "",
        },
    },
    // Booster Classic Collection [EX1] - Box Topper
    {
        "id": null,
        "name": "Booster Classic Collection [EX1] - Box Topper",
        "release": "December 10, 2021",
        "url": "digimoncardURL/setID-cardID_parallel.png",
        "cards": {
            "BT2-065": "P2",
        },
    },

// March 4, 2022
    // Booster Next Adventure [BT7]
    {
        "id": "BT7",
        "name": "Booster Next Adventure [BT7]",
        "release": "March 4, 2022",
        "total": 112,
        "url": "bandaitcgplusURL/setID/setID-cardID.png",
        "add_zero": 3,
        "override": {
            "url": "bandaitcgplusURL/setID/setID-cardIDp.png",
            "cards": {
                "BT7-017": ""
            }
        },
    },
    // Booster Next Adventure [BT7] - Alternatives
    {
        "id": null,
        "name": "Booster Next Adventure [BT7] - Alternatives",
        "release": "March 4, 2022",
        "url": "bandaitcgplusURL/setID/setID-cardIDp.png",
        "cards": {
            "BT7-008": "",
            "BT7-013": "",
            "BT7-016": "",
            "BT7-018": "",
            "BT7-019": "",
            "BT7-026": "",
            "BT7-029": "",
            "BT7-031": "",
            "BT7-040": "",
            "BT7-041": "",
            "BT7-044": "",
            "BT7-056": "",
            "BT7-063": "",
            "BT7-065": "",
            "BT7-068": "",
            "BT7-079": "",
            "BT7-111": "",
            "BT7-112": "",
        },
    },
    // Booster Next Adventure [BT7] - Box Topper
    {
        "id": null,
        "name": "Booster Next Adventure [BT7] - Box Topper",
        "release": "March 4, 2022",
        "url": "bandaitcgplusURL/setID/setID-cardIDp.png",
        "cards": {
            "BT7-085": "",
            "BT7-086": "",
            "BT7-087": "",
            "BT7-088": "",
            "BT7-089": "",
            "BT7-091": "",
        },
    },
    // Box Promotion Pack Next Adventure
    {
        "id": null,
        "name": "Box Promotion Pack Next Adventure",
        "release": "March 4, 2022",
        "url": "digimoncardURL/setID-cardID_parallel.png",
        "cards": {
            "P-035": "P1",
            "P-036": "P1",
            "P-037": "P1",
            "P-038": "P1",
            "P-039": "P1",
            "P-040": "P1",
        },
    },

// May, 2022
    // Tamer's Evolution Box2 [PB-06]
    {
        "id": null,
        "name": "Tamer's Evolution Box2 [PB-06]",
        "release": "February, 2021",
        "url": "digimonCardDev/setID-cardID_parallelen-US.jpg",
        "cards": {
            "BT2-033": "8f5499",
            "BT3-047": "a4198b",
            "BT4-011": "daf5da",
            "BT5-009": "1de00b",
            "EX1-013": "30d056",
            "EX1-071": "39f0e0",
            "P-001": "6e2082",
            "ST7-03": "d7cf43",
        },
        "info_url": "https://world.digimoncard.com/products/goods/evolution-box2.php"

    },

// May 13, 2022
    // Starter Deck ULTIMATE ANCIENT DRAGON [ST-9]
    {
        "id": "ST9",
        "name": "Starter Deck ULTIMATE ANCIENT DRAGON [ST-9]",
        "release": "May 13, 2022",
        "total": 16,
        "url": "bandaitcgplusURL/setID/e_ST09_cardID_D.jpg",
        "add_zero": 2,
        "info_url": "https://world.digimoncard.com/products/deck/st-9.php"
    },
    // Starter Deck PARALLEL WORLD TACTICIAN [ST-10]
    {
        "id": "ST10",
        "name": "Starter Deck PARALLEL WORLD TACTICIAN [ST-10]",
        "release": "May 13, 2022",
        "total": 16,
        "url": "bandaitcgplusURL/setID/e_setID_cardID_D.jpg",
        "add_zero": 2,
        "info_url": "https://world.digimoncard.com/products/deck/st-10.php"
    },

    // Booster New Awakening [BT8]
    {
        "id": "BT8",
        "name": "Booster New Awakening [BT8]",
        "release": "May 13, 2022",
        "total": 112,
        "url": "bandaitcgplusURL/setID/e_setID_cardID.png",
        "add_zero": 3,
    },
    // Booster New Awakening [BT8] - Alternatives
    {
        "id": null,
        "name": "Booster New Awakening [BT8] - Alternatives",
        "release": "May 13, 2022",
        "url": "bandaitcgplusURL/setID/e_setID_cardIDp.png",
        "cards": {
            "BT8-008": "",
            "BT8-009": "",
            "BT8-012": "",
            "BT8-026": "",
            "BT8-032": "",
            "BT8-033": "",
            "BT8-038": "",
            "BT8-039": "",
            "BT8-051": "",
            "BT8-057": "",
            "BT8-060": "",
            "BT8-069": "",
            "BT8-070": "",
            "BT8-082": "",
            "BT8-083": "",
            "BT8-084": "",
            "BT8-111": "",
            "BT8-112": "",
        },
    },
    // Booster New Awakening [BT8] - Box Topper
    {
        "id": null,
        "name": "Booster New Awakening [BT8] - Box Topper",
        "release": "May 13, 2022",
        "url": "bandaitcgplusURL/setID/e_setID_cardIDp.png",
        "cards": {
            "BT8-085": "",
            "BT8-087": "",
            "BT8-088": "",
            "BT8-089": "",
            "BT8-090": "",
            "BT8-091": "",
        },
    },
    // Booster New Awakening [BT8] - Promo Box Topper
    {
        "id": null,
        "name": "Booster New Awakening [BT8] - Promo Box Topper",
        "release": "May 13, 2022",
        "url": "bandaitcgplusURL/P/e_P-cardID_d.png",
        "cards": {
            "P-047": "",
            "P-048": "",
        },
    },

// June 24, 2022
    // Booster Digital Hazard [EX2]
    {
        "id": "EX2",
        "name": "Booster Digital Hazard [EX2]",
        "release": "June 24, 2022",
        "total": 74,
        "url": "bandaitcgplusURL/setID/setID-cardID_dummy.jpg",
        "add_zero": 3,
        "override": {
            "url": "bandaitcgplusURL/setID/setID-cardIDP_dummy.png",
            "cards": {
                "EX2-002": ""
            }
        },
    },
    // Booster Digital Hazard [EX2] - Alternatives
    {
        "id": null,
        "name": "Booster Digital Hazard [EX2] - Alternatives",
        "release": "June 24, 2022",
        "url": "bandaitcgplusURL/setID/setID-cardIDP_dummy.png",
        "cards": {
            "EX2-001": "",
            "EX2-003": "",
            "EX2-004": "",
            "EX2-006": "",
            "EX2-008": "",
            "EX2-011": "",
            "EX2-012": "",
            "EX2-017": "",
            "EX2-018": "",
            "EX2-019": "",
            "EX2-022": "",
            "EX2-024": "",
            "EX2-025": "",
            "EX2-029": "",
            "EX2-031": "",
            "EX2-035": "",
            "EX2-038": "",
            "EX2-039": "",
            "EX2-041": "",
            "EX2-043": "",
            "EX2-044": "",
            "EX2-045": "",
            "EX2-056": "",
            "EX2-058": "",
            "EX2-060": "",
            "EX2-061": "",
            "EX2-062": "",
            "EX2-065": "",
            "EX2-073": "",
            "EX2-074": "",
        },
    },
    // Booster Digital Hazard [EX2] - Box Topper
    {
        "id": null,
        "name": "Booster Digital Hazard [EX2] - Box Topper",
        "release": "June 24, 2022",
        "url": null,
        "cards": {
            "ST9-06": "https://s3.amazonaws.com/prod.bandaitcgplus.files.api/card_image/DG-EN/EX2/e_ST09-06P_D.png",
            "ST10-06": "https://s3.amazonaws.com/prod.bandaitcgplus.files.api/card_image/DG-EN/EX2/e_ST10-06P_D.png",
        },
    },

// June, 2022
    // Playmat and Card Set 1 -Digimon Tamers [PB-08]
    {
        "id": null,
        "name": "Playmat and Card Set 1 -Digimon Tamers [PB-08]",
        "release": "June, 2021",
        "url": "digimonCardDev/setID-cardID_parallelen-US.jpg",
        "cards": {
            "BT1-035": "913866",
            "BT2-009": "66dcd2",
            "BT2-068": "5e6f62",
            "BT3-046": "d9ac05",
            "BT3-057": "16e33c",
            "BT5-036": "fc6be2",
            "BT5-044": "25fe61",
            "ST7-09": "cd9977",
        },
        "info_url": "https://world.digimoncard.com/products/goods/playmat_digimon-tamers.php"

    },

// July 29, 2022
    // Booster X Record [BT9]
    {
        "id": "BT9",
        "name": "Booster X Record [BT9]",
        "release": "July 29, 2022",
        "total": 112,
        "url": "bandaitcgplusURL/setID/e_setID-cardID_dummy.jpg",
        "add_zero": 3
    },
    // Booster X Record [BT9] - Alternatives
    {
        "id": null,
        "name": "Booster X Record [BT9] - Alternatives",
        "release": "July 29, 2022",
        "url": "bandaitcgplusURL/setID/e_setID-cardIDP_dummy.jpg",
        "cards": {
            "BT9-008": "",
            "BT9-016": "",
            "BT9-017": "",
            "BT9-020": "",
            "BT9-021": "",
            "BT9-031": "",
            "BT9-044": "",
            "BT9-055": "",
            "BT9-064": "",
            "BT9-066": "",
            "BT9-068": "",
            "BT9-074": "",
            "BT9-080": "",
            "BT9-081": "",
            "BT9-082": "",
            "BT9-083": "",
            "BT9-111": "",
            "BT9-112": "",
        },
    },
    // Booster X Record [BT9] - Box Topper
    {
        "id": null,
        "name": "Booster X Record [BT9] - Box Topper",
        "release": "July 29, 2022",
        "url": "bandaitcgplusURL/setID/e_setID-cardIDP_dummy.jpg",
        "cards": {
            "BT9-001": "",
            "BT9-002": "",
            "BT9-003": "",
            "BT9-004": "",
            "BT9-005": "",
            "BT9-006": "",
        },
    },
    // Box Promotion Pack Update Pack
    {
        "id": null,
        "name": "Box Promotion Pack Update Pack",
        "release": "July 29, 2022",
        "url": "bandaitcgplusURL/setID/e_setID-cardID_Dparallel.png",
        "cards": {
            "P-072": ["", "_horo"],
            "P-073": ["", "_horo"],
            "P-074": ["", "_horo"],
            "P-075": ["", "_horo"],
            "P-076": ["", "_horo"],
            "P-077": ["", "_horo"],
        },
    },

// October 14, 2022
    // Starter Deck JESMON [ST-12]
    {
        "id": "ST12",
        "name": "Starter Deck JESMON [ST-12]",
        "release": "October 14, 2022",
        "total": 16,
        "url": "bandaitcgplusURL/setID/e_setID-cardID_D.png",
        "add_zero": 2,
        "info_url": "https://world.digimoncard.com/products/deck/st-12.php"
    },
    // Starter Deck RagnaLoardmon [ST-13]
    {
        "id": "ST13",
        "name": "Starter Deck RagnaLoardmon [ST-13]",
        "release": "October 14, 2022",
        "total": 16,
        "url": "bandaitcgplusURL/setID/e_setID-cardID_D.png",
        "add_zero": 2,
        "info_url": "https://world.digimoncard.com/products/deck/st-13.php"
    },
    // Bonus Tamer Cards Pack
    {
        "id": null,
        "name": "Bonus Tamer Cards Pack",
        "release": "October 14, 2022",
        "url": "bandaitcgplusURL/ST12/e_setID-cardIDparallel.png",
        "cards": {
            "ST1-12": "P_D",
            "ST3-12": "P_D",
            "ST6-14": "P_D",
            "BT3-093": "P_D",
            "BT3-094": "P_D",
            "BT4-096": "P2_D",
        },
    },

    // Booster Xros Encounter [BT10]
    {
        "id": "BT10",
        "name": "Booster Xros Encounter [BT10]",
        "release": "October 14, 2022",
        "total": 112,
        "url": "bandaitcgplusURL/setID/e_setID-cardID_D.png",
        "add_zero": 3
    },
    // Booster Xros Encounter [BT10] - Alternatives
    {
        "id": null,
        "name": "Booster Xros Encounter [BT10] - Alternatives",
        "release": "October 14, 2022",
        "url": "bandaitcgplusURL/BT10/e_setID-cardIDp_D.png",
        "cards": {
            "BT10-011": "",
            "BT10-013": "",
            "BT10-016": "",
            "BT10-023": "",
            "BT10-024": "",
            "BT10-026": "",
            "BT10-041": "",
            "BT10-042": "",
            "BT10-044": "",
            "BT10-054": "",
            "BT10-057": "",
            "BT10-060": "",
            "BT10-068": "",
            "BT10-069": "",
            "BT10-082": "",
            "BT10-083": "",
            "BT10-085": "",
            "BT10-086": "",
            "BT10-111": "",
            "BT10-112": "",
            "BT6-111": "",
        },
    },
    // Booster Xros Encounter [BT10] - Box Topper
    {
        "id": null,
        "name": "Booster Xros Encounter [BT10] - Box Topper",
        "release": "October 14, 2022",
        "url": "bandaitcgplusURL/BT10/e_setID-cardIDp_D.png",
        "cards": {
            "BT10-087": "",
            "BT10-088": "",
            "BT10-089": "",
            "BT10-090": "",
            "BT10-092": "",
            "BT10-093": "",
        },
    },
    // Box Promotion Pack ST-11 Special Entry pack
    {
        "id": null,
        "name": "Box Promotion Pack ST-11 Special Entry pack",
        "release": "October 14, 2022",
        "url": "digimonCardDev/setID-cardID_parallelen-US.jpg",
        "cards": {
            "P-065": "c2a5dd",
            "ST1-03": "825143",
            "ST1-07": "4b607f",
            "ST1-16": "b68c9b",
            "BT1-023": "004865",
            "BT1-025": "6ab4c9",
            "BT1-085": "2eaa63",
            "BT2-001": "ce2c17",
            "BT2-010": "9f66f1",
            "BT2-011": "728ad2",
            "BT2-016": "685e61",
            "BT2-018": "de1f61",
            "BT3-009": "4b790f",
            "BT4-010": "b81554",
            "BT4-015": "e6ee13",
            "BT4-099": "51fe95",
            "BT5-012": "bc0a8b",
        },
    },
    // 25th Special Memorial Pack
    {
        "id": null,
        "name": "25th Special Memorial Pack",
        "release": "October 14, 2022",
        "url": "digimonCardDev/setID-cardID_parallelen-US.jpg",
        "cards": {
            "P-018": "b6bb28",
            "BT1-010": "75d9b6",
            "BT1-038": "914853",
            "BT2-024": "d8aa0f",
            "BT2-044": "c18a29",
            "BT2-056": "4ac4e5",
            "BT3-024": "59f192",
            "BT5-010": "643e1e",
            "BT5-011": "fe716a",
            "BT6-064": "16d9cb",
            "BT7-044": "91c358",
            "BT8-067": "3c9d1a",
        },
    },
    
// November 11, 2022
    // Booster Draconic Roar [EX3]
    {
        "id": "EX3",
        "name": "Booster Draconic Roar [EX3]",
        "release": "November 11, 2022",
        "total": 74,
        "url": "bandaitcgplusURL/setID/e_setID-cardID_D.png",
        "add_zero": 3,
        "override": {
            "url": "bandaitcgplusURL/setID/setID-cardID_D.png",
            "cards": {
                "EX3-013": ""
            }
        },
    },
    // Booster Draconic Roar [EX3] - Alternatives
    {
        "id": null,
        "name": "Booster Draconic Roar [EX3] - Alternatives",
        "release": "November 11, 2022",
        "url": "bandaitcgplusURL/setID/e_setID-cardIDp_D.png",
        "cards": {
            "EX3-012": "",
            "EX3-013": "",
            "EX3-014": "",
            "EX3-024": "",
            "EX3-025": "",
            "EX3-026": "",
            "EX3-035": "",
            "EX3-036": "",
            "EX3-037": "",
            "EX3-044": "",
            "EX3-045": "",
            "EX3-053": "",
            "EX3-054": "",
            "EX3-063": "",
            "EX3-064": "",
            "EX3-065": "",
            "EX3-073": "",
            "EX3-074": "",
        },
    },
    // Booster Draconic Roar [EX3] - Box Topper
    {
        "id": null,
        "name": "Booster Draconic Roar [EX3] - Box Topper",
        "release": "November 11, 2022",
        "url": null,
        "cards": {
            "BT3-111": "https://assets.cardlist.dev/images/communitycards/BT3-111_b69739en-US.jpg",
            // "EX3-10": "",
            // "EX3-20": "",
            // "EX3-31": "",
            // "EX3-41": "",
            // "EX3-49": "",
            // "EX3-61": "",
        },
    },

    // Event Pack 1
    {
        "id": null,
        "name": "Event Pack 1",
        "release": null,
        "url": "bandaitcgplusURL/setID/setID-cardID_parallel.png",
        "cards": {
            "ST1-02": "P1",
            "ST1-06": "P1",
            "ST1-11": "P2",
            "ST2-02": "P1",
            "ST2-07": "P1",
            "ST2-11": "P1",
            "ST3-02": "P1",
            "ST3-07": "P1",
            "BT1-064": "P1",
            "BT1-072": "P1",
            "BT1-077": "P1",
            "BT2-072": "P1",
            "BT3-059": "P1",
            "BT3-076": "P1",
            "BT4-005": "P1",
            "BT4-067": "P1",
            "BT4-088": "P2",
            "BT5-045": "P1",
        }
    }
];